sudo: required
language: python

cache:
    apt: true
    pip: true

matrix:
    include:
        - python: 3.6
          dist: focal
        - python: 3.7
          dist: focal
        - python: 3.8
          dist: focal

before_install:
    - sudo apt-get update
    - sudo updatedb

install:
    - pip install --progress-bar off ipython
    - pip install --progress-bar off nose
    - pip install --progress-bar off nose-exclude
    - pip install --progress-bar off coverage
    - pip install --progress-bar off coveralls
    - pip install --progress-bar off pycodestyle
    - pip install --progress-bar off .

script:
    - python setup.py nosetests
    - pycodestyle brainprep --ignore="E121,E123,E126,E226,E24,E704,E402,E731,E722,E741,W503,W504,W605"

after_success:
    - coveralls

