# ---------- Global Build Arguments ----------
ARG MAKE_JOBS="1"
ARG DEBIAN_FRONTEND="noninteractive"

# ---------- Base Stage: Core Dependencies ----------
FROM ubuntu:24.04 AS base
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        python3 \
        tar \
        unzip \
        wget
ENV PATH="/root/.pixi/bin:${PATH}"
RUN curl -fsSL https://pixi.sh/install.sh | bash \
    && pixi --version


# ---------- Downloader Stages (Parallelizable) ----------
# AAL Downloader
FROM base AS aal-downloader
WORKDIR /opt/aal
RUN wget --no-check-certificate \
        https://data.kg.ebrains.eu/zip?container=https://data-proxy.ebrains.eu/api/v1/buckets/p4791e-ext-d000035_AAL1Atlas_pub?prefix=Release2018_SPM12 \
       -O aal1_for_SPM12.zip \
   && unzip aal1_for_SPM12.zip \
   && rm -f aal1_for_SPM12.zip \
   && unzip aal_for_SPM12.zip \
   && rm -f aal_for_SPM12.zip \
   && mv aal_for_SPM12/* . \
   && rmdir aal_for_SPM12 \
   && rm -rf __MACOSX \
   && wget --no-check-certificate -qO- http://www.gin.cnrs.fr/wp-content/uploads/aal2_for_SPM12.tar.gz | \
      tar zx --strip-components=1

# ADHD200 Downloader
FROM base AS adhd200-downloader
WORKDIR /opt
RUN wget --no-check-certificate -qO- http://www.nitrc.org/frs/download.php/5906/ADHD200_parcellations.tar.gz | \
    tar zx \
    && rm -f ADHD200_parcellations.tar.gz

# BrainNetome Downloader
FROM base AS brainnetome-downloader
WORKDIR /opt/brainnetome
RUN \
   ( curl https://pan.cstcloud.cn/unode/stor/downloadByUrl?downloadId=1.eyJidWNrZXQiOiJkZWZhdWx0IiwibGVuIjozODIzMDY1Nywic2l6ZSI6MzgyMzA2NTcsInBvcyI6MCwibmFtZSI6InJoLkJOX0F0bGFzLmdjcyIsImN0aW1lIjoxNzYxNjE3OTkyLCJrZXkiOiJzTEhJaHcxYkZYZ0RTeGRld3I0ZWtxRjJuQ0VBQUFBQ1IxcUIiLCJhZ2UiOjg2NDAwfQ.3670708009 \
            -o rh.BN_Atlas.gcs || \
       wget --no-check-certificate -q "https://osf.io/e6zkg/download" -O rh.BN_Atlas.gcs ) \
   && ( curl https://pan.cstcloud.cn/unode/stor/downloadByUrl?downloadId=1.eyJidWNrZXQiOiJkZWZhdWx0IiwibGVuIjozNjQ5NzM5OSwic2l6ZSI6MzY0OTczOTksInBvcyI6MCwibmFtZSI6ImxoLkJOX0F0bGFzLmdjcyIsImN0aW1lIjoxNzYxNjE3OTEwLCJrZXkiOiJsMzFISVJNZ3FScXZlREg4S2RPVjRqUXNVRnNBQUFBQ0xPZjMiLCJhZ2UiOjg2NDAwfQ.4292748252 \
            -o lh.BN_Atlas.gcs || \
       wget --no-check-certificate -q "https://osf.io/af9ut/download" -O lh.BN_Atlas.gcs ) \
   && ( curl https://pan.cstcloud.cn/unode/stor/downloadByUrl?downloadId=1.eyJidWNrZXQiOiJkZWZhdWx0IiwibGVuIjozNzAxODQwOCwic2l6ZSI6MzcwMTg0MDgsInBvcyI6MCwibmFtZSI6IkJOX0F0bGFzX3N1YmNvcnRleC5nY2EiLCJjdGltZSI6MTc2MTYxODA2Niwia2V5IjoicEhiTXdwbjBKRUd4cmJ2Z0NScDFTdzNsS2RrQUFBQUNOTnNvIiwiYWdlIjo4NjQwMH0.1891919902 \
            -o BN_Atlas_subcortex.gca || \
       wget --no-check-certificate -q "https://osf.io/k2cd8/download" -O BN_Atlas_subcortex.gca ) \
   && ( curl https://pan.cstcloud.cn/unode/stor/downloadByUrl?downloadId=1.eyJidWNrZXQiOiJkZWZhdWx0IiwibGVuIjo1ODAyLCJzaXplIjo1ODAyLCJwb3MiOjAsIm5hbWUiOiJCTl9BdGxhc18yNDZfTFVULnR4dCIsImN0aW1lIjoxNzYxNjE4MDkwLCJrZXkiOiJ1bGV4dG1Kd0hJeGNjdVFDZWwzdTZnUVJXUThBQUJhcSIsImFnZSI6ODY0MDAsInBhcnRPbmUiOnsic2l6ZSI6NTgwMiwiZm4iOiJoa194MmRaLVFYZy0wLTU4MDIiLCJjcmMzMiI6ODk4MzQwOTA0LCJiaWQiOjEsImNpZCI6MX19.3302844208 \
            -o BN_Atlas_246_LUT.txt || \
       wget --no-check-certificate -q "https://osf.io/eb7pm/download" -O BN_Atlas_246_LUT.txt ) \
   && ( curl https://pan.cstcloud.cn/unode/stor/downloadByUrl?downloadId=1.eyJidWNrZXQiOiJkZWZhdWx0IiwibGVuIjoxNzEyMzMsInNpemUiOjE3MTIzMywicG9zIjowLCJuYW1lIjoiQk5BX01QTV90aHIyNV8xLjI1bW0ubmlpLmd6IiwiY3RpbWUiOjE3NjE2MTk3NzcsImtleSI6IlFrbzBFajRIRTEyS1U4N0tBOXdVZlVMX1RIY0FBcHpoIiwiYWdlIjo4NjQwMCwicGFydE9uZSI6eyJzaXplIjoxNzEyMzMsImZuIjoibDlsX3ZVVkRRMDAtMC0xNzEyMzMiLCJjcmMzMiI6MjY1NjI1NTM0NywiYmlkIjoxLCJjaWQiOjF9fQ.2692886444 \
            -o BNA_MPM_thr25_1.25mm.nii.gz || \
       wget --no-check-certificate -q "https://osf.io/dbqep/download" -O BNA_MPM_thr25_1.25mm.nii.gz )

# MNI Downloader
FROM base AS mni512-downloader
WORKDIR /opt
RUN wget --no-check-certificate -q https://github.com/AlistairPerry/CCA/raw/master/parcellations/512inMNI.nii

# Yeo2011 Downloader
FROM base AS yeo2011-downloader
WORKDIR /opt/Yeo2011
RUN wget --no-check-certificate -qO- "https://github.com/ThomasYeoLab/CBIG/archive/v0.11.1-Wu2017_RegistrationFusion.tar.gz" | \
    tar zx \
    && mkdir -p freesurfer/subjects/fsaverage5/label \
    && cp CBIG-0.11.1-Wu2017_RegistrationFusion/stable_projects/brain_parcellation/Yeo2011_fcMRI_clustering/1000subjects_reference/Yeo_JNeurophysiol11_SplitLabels/fsaverage5/label/*h.Yeo2011_*Networks_N1000.split_components.annot freesurfer/subjects/fsaverage5/label/ \
    && cp CBIG-0.11.1-Wu2017_RegistrationFusion/stable_projects/brain_parcellation/Yeo2011_fcMRI_clustering/1000subjects_reference/Yeo_JNeurophysiol11_SplitLabels/project_to_individual/Yeo2011_*networks_Split_Components_LUT.txt freesurfer/ \
    && cp CBIG-0.11.1-Wu2017_RegistrationFusion/stable_projects/brain_parcellation/Yeo2011_fcMRI_clustering/1000subjects_reference/Yeo_JNeurophysiol11_SplitLabels/MNI152/Yeo2011_*Networks_N1000.split_components.FSL_MNI152_*mm.nii.gz . \
    && cp CBIG-0.11.1-Wu2017_RegistrationFusion/stable_projects/brain_parcellation/Yeo2011_fcMRI_clustering/1000subjects_reference/Yeo_JNeurophysiol11_SplitLabels/MNI152/*Networks_ColorLUT_freeview.txt . \
    && rm -rf CBIG-0.11.1-Wu2017_RegistrationFusion

# ---------- Tool-Specific Stages ----------
# ANTs Installer
FROM base AS ants-installer
WORKDIR /opt/ants
RUN wget --no-check-certificate -q https://github.com/ANTsX/ANTs/releases/download/v2.6.2/ants-2.6.2-ubuntu18.04-X64-gcc.zip \
   && unzip ants-2.6.2-ubuntu18.04-X64-gcc.zip

# FreeSurfer Installer
FROM base AS freesurfer-installer
RUN wget --no-check-certificate -qO- https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.4.1/freesurfer-linux-centos8_x86_64-7.4.1.tar.gz | \
   tar zx -C /opt \
   --exclude='freesurfer/trctrain' \
   --exclude='freesurfer/subjects/fsaverage_sym' \
   --exclude='freesurfer/subjects/fsaverage3' \
   --exclude='freesurfer/subjects/fsaverage4' \
   --exclude='freesurfer/subjects/fsaverage6' \
   --exclude='freesurfer/subjects/cvs_avg35' \
   --exclude='freesurfer/subjects/cvs_avg35_inMNI152' \
   --exclude='freesurfer/subjects/bert' \
   --exclude='freesurfer/subjects/V1_average' \
   --exclude='freesurfer/average/mult-comp-cor' \
   --exclude='freesurfer/lib/cuda' \
   --exclude='freesurfer/lib/qt'
RUN wget --no-check-certificate -q "https://s3-eu-west-1.amazonaws.com/pfigshare-u-files/5528816/lh.HCPMMP1.annot" \
        -O /opt/freesurfer/subjects/fsaverage/label/lh.HCPMMP1.annot \
   && wget --no-check-certificate -q "https://s3-eu-west-1.amazonaws.com/pfigshare-u-files/5528819/rh.HCPMMP1.annot" \
        -O /opt/freesurfer/subjects/fsaverage/label/rh.HCPMMP1.annot
RUN echo "cHJpbnRmICJyb2JlcnQuc21pdGhAZmxvcmV5LmVkdS5hdVxuMjg1NjdcbiAqQ3FLLjFwTXY4ZE5rXG4gRlNvbGRZRXRDUFZqNlxuIiA+IC9vcHQvZnJlZXN1cmZlci9saWNlbnNlLnR4dAo=" | base64 -d | sh

# FSL Installer
FROM base AS fsl-installer
WORKDIR /
RUN wget -q http://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py \
   && chmod 775 fslinstaller.py \
   && python3 /fslinstaller.py -d /opt/fsl -V 6.0.7.18

# MRtrix3 Installer: MRtrix3 #3029 as at 2025-10-21
FROM base AS mrtrix-installer
WORKDIR /opt/mrtrix3
RUN apt-get install -y \
        build-essential \
        cmake \
        git \
        libfftw3-dev \
        ninja-build \
        pkg-config \
        zlib1g-dev
RUN git clone https://github.com/MRtrix3/mrtrix3.git . \
    && git checkout 26965d57b374a733ac0c583d3b92bad17923128a
RUN git clone https://github.com/Lestropie/dwidenoise2.git dwidenoise2 \
    && cd dwidenoise2 \
    && git checkout a2da5b32876256499a383a52494ca6564009ca85 \
    && cd ../ \
    && cp -r dwidenoise2/cpp .
COPY mrtrix3_connectome/ /opt/mrtrix3/python/mrtrix3/commands/mrtrix3_connectome
RUN cmake -Bbuild -GNinja --preset=release -DMRTRIX_BUILD_GUI=OFF \
    && cmake --build build

# ROBEX Installer
FROM base AS robex-installer
WORKDIR /opt/robex
RUN wget --no-check-certificate -qO- "https://www.nitrc.org/frs/download.php/5994/ROBEXv12.linux64.tar.gz//?i_agree=1&download_now=1" | \
    tar zx

# Geolab Installer
FROM base AS geolab-installer
WORKDIR /opt/geolab
RUN apt-get install -y \
        build-essential \
        git \
        libboost-all-dev \
        libeigen3-dev \
        libncurses5-dev \
        libncursesw5-dev
RUN pixi init \
    && pixi add \
        python==3.12 \
        numpy \
    && pixi add --pypi  \
        setproctitle>=1.2.3 \
        fitter>=1.5.1 \
        nibabel>=3.2.2 \
    && pixi add \
        ncurses \
        boost \
        eigen \
        openmp \
    && pixi add \
        gcc_linux-64 \
        gxx_linux-64 \
        cmake==3.20.2 \
        make pkg-config
RUN git clone --depth 1 https://github.com/vindasna/GeoLab ./code \
    && cd code \
    && git fetch --depth 1 origin f5de43c05b3eeb20823f647d271f6e845c4f6d4b \
    && git checkout f5de43c05b3eeb20823f647d271f6e845c4f6d4b
RUN rm -r code/build \
    && mkdir code/build \
    && cd code/build \
    && pixi run cmake .. \
    && pixi run make -j"$(nproc)"
COPY ./Atlas/short /opt/geolab/atlas/short
RUN echo '\n[activation.env]' >> pixi.toml \
    && echo 'PATH="/opt/geolab/code/build/bin:${PATH}"' >> pixi.toml \
    && echo 'PYTHONPATH="/opt/geolab/code:${PYTHONPATH}"' >> pixi.toml \
    && echo 'ESBA_DIR="/opt/geolab/atlas/short"' >> pixi.toml

# Tractseg Installer
FROM base AS tractseg-installer
WORKDIR /opt/tractseg
RUN ls /root/.pixi/bin
RUN pixi init \
    && pixi add \
        python==3.12 \
        dipy==1.12.1 \
        libgl \
        xorg-libxrender \
    && pixi add --pypi \
        torch==2.11.0 \
        TractSeg==2.10

# Synb0 Installer
FROM base AS synb0-installer
WORKDIR /opt/convert3d
RUN wget --no-check-certificate -O c3d-1.0.0-Linux-x86_64.tar.gz "https://downloads.sourceforge.net/project/c3d/c3d/1.0.0/c3d-1.0.0-Linux-x86_64.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fc3d%2Ffiles%2Fc3d%2F1.0.0%2Fc3d-1.0.0-Linux-x86_64.tar.gz%2Fdownload&ts=1571934949" \
   && tar -xf c3d-1.0.0-Linux-x86_64.tar.gz \
   && rm c3d-1.0.0-Linux-x86_64.tar.gz
WORKDIR /opt/synb0
RUN pixi init \
    && pixi add \
        python==3.6.15 \
    && pixi add --pypi \
        nibabel==2.4.0 \
        numpy==1.16.3 \
        Pillow==6.0.0 \
        # pkg-resources==0.0.0 \
        scipy==1.3.0 \
        six==1.12.0 \
        torch==1.1.0 \
        torchvision==0.2.2.post3
COPY synb0/ .

# ---------- Final Stage ----------
FROM base AS final

# Install system dependencies (minimal)
RUN apt-get -qq update \
    && apt-get install -yq --no-install-recommends \
        bc \
        dc \
        git \
        libfftw3-single3 \
        libfftw3-double3 \
        nano \
        nodejs \
        npm \
        tcsh \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Copy artifacts from builder stages
COPY --from=aal-downloader /opt/aal /opt/aal
COPY --from=adhd200-downloader /opt/ADHD200_parcellate_200.nii.gz /opt/ADHD200_parcellate_200.nii.gz
COPY --from=adhd200-downloader /opt/ADHD200_parcellate_400.nii.gz /opt/ADHD200_parcellate_400.nii.gz
COPY --from=ants-installer /opt/ants/ants-2.6.2 /opt/ants
COPY --from=brainnetome-downloader /opt/brainnetome/rh.BN_Atlas.gcs /opt/freesurfer/average/rh.BN_Atlas.gcs
COPY --from=brainnetome-downloader /opt/brainnetome/lh.BN_Atlas.gcs /opt/freesurfer/average/lh.BN_Atlas.gcs
COPY --from=brainnetome-downloader /opt/brainnetome/BN_Atlas_subcortex.gca /opt/freesurfer/average/BN_Atlas_subcortex.gca
COPY --from=brainnetome-downloader /opt/brainnetome/BN_Atlas_246_LUT.txt /opt/brainnetome/BN_Atlas_246_LUT.txt
COPY --from=brainnetome-downloader /opt/brainnetome/BN_Atlas_246_LUT.txt /opt/freesurfer/BN_Atlas_246_LUT.txt
COPY --from=brainnetome-downloader /opt/brainnetome/BNA_MPM_thr25_1.25mm.nii.gz /opt/brainnetome/BNA_MPM_thr25_1.25mm.nii.gz
COPY --from=mni512-downloader /opt/512inMNI.nii /opt/512inMNI.nii
COPY --from=yeo2011-downloader /opt/Yeo2011 /opt/Yeo2011
COPY --from=freesurfer-installer /opt/freesurfer /opt/freesurfer
COPY --from=fsl-installer /opt/fsl /opt/fsl
COPY --from=mrtrix-installer /opt/mrtrix3 /opt/mrtrix3
COPY --from=robex-installer /opt/robex /opt/robex
COPY --from=geolab-installer /opt/geolab /opt/geolab
COPY --from=tractseg-installer /opt/tractseg /opt/tractseg
COPY --from=synb0-installer /opt/synb0 /opt/synb0
COPY --from=synb0-installer /opt/convert3d /opt/convert3d

# Move Yeo2011 files to FreeSurfer
RUN mv /opt/Yeo2011/freesurfer/subjects/fsaverage5/label/* /opt/freesurfer/subjects/fsaverage5/label \
    && mv /opt/Yeo2011/freesurfer/*.* /opt/freesurfer/ \
    && rm -rf /opt/Yeo2011/freesurfer

# Install bids-validator
RUN npm install -gq bids-validator@1.15.0

# Geolab command
RUN echo '#!/bin/bash' > /usr/local/bin/ProjectAtlasGeoLab && \
    echo 'pixi run -m /opt/geolab/pixi.toml ProjectAtlasGeoLab "$@"' >> /usr/local/bin/ProjectAtlasGeoLab && \
    chmod +x /usr/local/bin/ProjectAtlasGeoLab
RUN echo '#!/bin/bash' > /usr/local/bin/ConvertBundleFormat && \
    echo 'pixi run -m /opt/geolab/pixi.toml ConvertBundleFormat "$@"' >> /usr/local/bin/ConvertBundleFormat && \
    chmod +x /usr/local/bin/ConvertBundleFormat

# Tractseg command
RUN echo '#!/bin/bash' > /usr/local/bin/TractSeg && \
    echo 'pixi run  --as-is -m /opt/tractseg/pixi.toml TractSeg "$@"' >> /usr/local/bin/TractSeg && \
    chmod +x /usr/local/bin/TractSeg
RUN echo '#!/bin/bash' > /usr/local/bin/Tracking && \
    echo 'pixi run --as-is -m /opt/tractseg/pixi.toml Tracking "$@"' >> /usr/local/bin/Tracking && \
    chmod +x /usr/local/bin/Tracking
RUN echo '#!/bin/bash' > /usr/local/bin/Tractometry && \
    echo 'pixi run --as-is -m /opt/tractseg/pixi.toml Tractometry "$@"' >> /usr/local/bin/Tractometry && \
    chmod +x /usr/local/bin/Tractometry

# Synb0  command
ENV PATH="/opt/convert3d/c3d-1.0.0-Linux-x86_64/bin:$PATH"
RUN echo '#!/bin/bash' > /usr/local/bin/synb0 && \
    echo 'pixi run  --as-is -m /opt/synb0/pixi.toml /opt/synb0/synb0.sh "$@"' >> /usr/local/bin/synb0 && \
    chmod +x /usr/local/bin/synb0

# Install BrainPrep & AMICO
WORKDIR /opt/brainprep
COPY pixi.toml .
RUN pixi install \
    && pixi add --pypi \
        dmri-amico==2.1.1
RUN ln -s /opt/brainprep/.pixi/envs/default/bin/brainprep /usr/local/bin/brainprep

# Environment Variables
ENV ANTSPATH=/opt/ants \
    FREESURFER_HOME=/opt/freesurfer \
    FMRI_ANALYSIS_DIR=/opt/freesurfer/fsfast \
    FSF_OUTPUT_FORMAT=nii.gz \
    FSFAST_HOME=/opt/freesurfer/fsfast \
    LOCAL_DIR=/opt/freesurfer/local \
    MINC_BIN_DIR=/opt/freesurfer/mni/bin \
    MINC_LIB_DIR=/opt/freesurfer/mni/lib \
    MNI_DATAPATH=/opt/freesurfer/mni/data \
    MNI_DIR=/opt/freesurfer/mni \
    MNI_PERL5LIB=/opt/freesurfer/mni/lib/perl5/5.8.5 \
    OS=Linux \
    PERL5LIB=/opt/freesurfer/mni/lib/perl5/5.8.5 \
    SUBJECTS_DIR=/opt/freesurfer/subjects \
    FSLDIR=/opt/fsl \
    FSLOUTPUTTYPE=NIFTI \
    FSLMULTIFILEQUIT=TRUE \
    FSLTCLSH=/opt/fsl/bin/fsltclsh \
    FSLWISH=/opt/fsl/bin/fslwish \
    ESBA_DIR=/opt/geolab/atlas/short \
    PATH=/opt/mrtrix3/build/bin:/opt/ants/bin:/opt/freesurfer/bin:/opt/freesurfer/mni/bin:/opt/fsl/bin:/opt/ROBEX:/opt/geolab/code/build/bin:$PATH \
    PYTHONPATH=/opt/mrtrix3/lib

# Entrypoint
COPY entrypoint.sh /opt/entrypoint.sh
RUN chmod +x /opt/entrypoint.sh
ENTRYPOINT ["/opt/entrypoint.sh"]
ENV DEFAULT_ARGS="subject-level-dmriprep group-level-dmriprep"

# Metadata
LABEL org.opencontainers.image.title="BrainPrep dMRI PreProcessing" \
      org.opencontainers.image.description="Container for BrainPrep dMRI PreProcessing using MrTrix3, GeoLab, TractSeg, FSL, Amico, SynB0" \
      org.opencontainers.image.version="v2" \
      org.opencontainers.image.licenses="CeCILL-B" \
      org.opencontainers.image.authors="CEA/NeuroSpin/GAIA" \
      org.opencontainers.image.documentation="https://brainprepdesk.github.io/brainprep/stable" \
      org.opencontainers.image.source="https://github.com/brainprepdesk/brainprep" \
      org.opencontainers.image.created="2025-01-15" \
      com.brainprep.fsl.version="6.0.7.18" \
      com.brainprep.mrtrix3.version="26965d" \
      com.brainprep.mrtrix3_connectome.version="dev" \
      com.brainprep.geolab.version="f5de43" \
      com.brainprep.tractseg.version="2.10" \
      com.brainprep.amico.version="2.1.1" \
      com.brainprep.synb0.version="dev"
